### ISSUE TITLE
lowPriority is not exactly a no-op like documentation say

### ISSUE THREAD

**Issue by keul** [YurkaninRyan/react-sentinel#2]
First of all, please please let me thank you for this great project. This saved me an huge amount of work!🍻 

----

Now the issue: about `lowPriority` documentation say "...For browsers that don't support requestIdleCallback this is basically a no-op" but this is not true.

If I use the lowPriority prop on Safari I get a "_Can't find variable requestIdleCallback_"

See https://github.com/YurkaninRyan/react-sentinel/blob/f899610c4a9aa714034c13a3ea8d38f15b65425e/src/react-sentinel.js#L30

I think that issue can be fixed by simply testing the existence on the window object.

**Comment by YurkaninRyan** [comment]
Hey Keul,

Thanks so much for making this issue.  Should be fixed in 0.1.8.
