### ISSUE TITLE
Lowering rate of calls to requestIdleCallback

### ISSUE THREAD

**Issue by keul** [YurkaninRyan/react-sentinel#4]
Although the use of `requestIdleCallback` is working exactly as expected and my application is not suffering any visible issue, while running the Chrome JavaScript profiler I see an high recorded time spent on calling this function (about 20% of the total) even if the app is not doing anything.

I'm wondering if could be helpful to provide a way (a props) that lower the call rate. Maybe simply using this prop at this line:

https://github.com/YurkaninRyan/react-sentinel/blob/cf2bc668929bb8a5b52a964ad436bdb7bbcbf1e4/src/react-sentinel.js#L57

The default to 0 is probably OK.

**Comment by YurkaninRyan** [comment]
@keul Ah yes, i've been thinking about this one for awhile.  I've considered exporting the check like functions, so you could feed them to react-sentinel wrapped in a debounce, or write your own custom one!

Thanks for making the issue i'll look into how I can update this

**Comment by YurkaninRyan** [comment]
@keul in 0.2.0 you can now pass in an `interval` prop.  So if you want it to check for updates every 3000ms you can do that!  Cheers, and let me know if you run into an issues with the upgrade.

**Comment by keul** [comment]
@YurkaninRyan working as expected! In my usecase just using `interval={100}` lowered CPU usage to 8%!
Thank you!

Can you release it this npm too?
